### ISSUE TITLE
Facing problem while installing specific Numpy version

### ISSUE THREAD

**Issue by subramanyakrishna** [LaJoKoch/SynthTextGerman#1]
Hello Sir, We were doing a similar project , So we tried running various Synthtext repositories which are  mentioned in the readme,md of Ankush/SythText But we are facing  numerous errors while installing, We are trying from a week to install packages and run , We had problem always, Since this is the recently updated repository we tried installing packages mentioned here,  But we are getting microsoft visual build failure even though we installed it, Can you please help us sir?

**Comment by LaJoKoch** [comment]
Hello, without a specific error message, I'm not sure what could be the reason for the problem. Below I've listed you all packages of my environment for the SynthText project. Maybe this will help you if the problem is related to the versions of installed packages. 
I remember that the version of pygame was important to get correct bounding boxes. That's also mentioned in an issue of the original repository.

ca-certificates-------------2020.12.5
certifi----------------------2020.12.5
cycler----------------------0.10.0
h5py-----------------------3.2.1
kiwisolver-----------------1.3.1
matplotlib-----------------3.4.1
numpy--------------------1.20.2
opencv-contrib-python--4.5.1.48
openssl-------------------1.1.1k 
pillow---------------------8.2.0
pip------------------------21.1
pygame------------------1.9.6
pyparsing-----------------2.4.7
python--------------------3.8.5
python-dateutil----------2.8.1
python-wget-------------3.2
python_abi---------------3.8
pytz----------------------2021.1
scipy---------------------1.6.2
setuptools---------------49.6.0
six------------------------1.15.0
snakeviz------------------2.1.0
sqlite---------------------3.35.4
tornado------------------6.1
vc------------------------14.2
vs2015_runtime---------14.27.29016
wheel--------------------0.36.2
wincertstore-------------0.2

**Comment by subramanyakrishna** [comment]
Thanks a lot for Replying Sir, Yes , I was able to install above mentioned packages , Thanks  for your help  .
